config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('courses/', include('courses.urls')),
    path('user/', include('users.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/urls.py
from django.urls import path
from .views import CategoriesView, CoursesView, CoursesModelView, GroupModelView, CourseDetailView

app_name = 'courses'

urlpatterns = [
    path('', CoursesModelView.as_view(), name='all'),
    path('categories/', CategoriesView, name='categories'),
    path('<int:pk>/', CourseDetailView.as_view(), name='course-detail'),
    path('groups/', GroupModelView.as_view(), name='groups')
]

main/urls.py
from django.urls import path

from .views import HomeView, ContactView, ContactCreateView

app_name = 'main'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('contact/create/', ContactCreateView.as_view(), name='contact_create'),

]

users/urls.py
from django.contrib.auth.views import PasswordResetView
from django.urls import path
from .views import ProfileView
from .views import login_view, logout_view

app_name = 'users'

urlpatterns = [
    path('profile/', ProfileView, name='profile'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
]

templates/layouts/inc/footer.html
{% load static %}

<!-- Footer Section Begin -->
<footer class="footer">
    <div class="container py-3 my-4">

        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Courses</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Blog</a></li>
        </ul>


        <div class="col-lg-12 d-flex align-items-center justify-content-end">
            <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                <a class="navbar-brand" href="#"><img src="{% static 'main/logo.png' %}" alt="">
                </a>
            </a>
            <div class="col-9"></div>
            <ul class="nav col-lg-2 justify-content-end list-unstyled d-flex">
                <li class="me-5 px-2"><a class="text" href="#"><img src="{% static 'main/telegram.png' %}" alt=""></a></li>
                <li class="me-5 px-2"><a class="text" href="#"><img src="{% static 'main/instagram.png' %}" alt=""></a></li>
                <li class="me-5 px-2"><a class="text" href="#"><img src="{% static 'main/facebook.png' %}" alt=""></a></li>
            </ul>
        </div>
    </div>
</footer>

templates/layouts/inc/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-light">
    <div class="container">
        <a class="navbar-brand" href="#"><img src="{% static 'main/logo.png' %}" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'main:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'courses:all' %}">Courses</a>
                </li>
                {% if not request.user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'users:login' %}" class="nav-link">Login</a>
                    </li>
                {% else %}

                    <li class="nav-item">
                        <a href="{% url 'users:profile' %}" class="nav-link">Profile</a>
                    </li>

                    <li class="nav-item">
                        <a href="{% url 'courses:groups' %}" class="nav-link">Groups</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'users:logout' %}" class="nav-link">Logout</a>
                    </li>

                {% endif %}
            </ul>
        </div>
    </div>
</nav>